apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    app: web-server
    team: product
    environment: development
  annotations:
    description: Ini adalah aplikasi yg dibuat oleh team product
    apapun: apapun itu lalalala yeyeyye...
spec:
  containers:
    - name: nginx
      image: nginx:1.18-alpine
      ports:
        - containerPort: 80
